---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Install aptitude
    apt: pkg=aptitude state=present update_cache=true

- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Configure the package manager to include accommodations for i386 architecture
      shell: dpkg --add-architecture i386
      ignore_errors: True

- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: apt update
      apt: update-cache=yes cache_valid_time=3600
      retries: 3
      delay: 1
      ignore_errors: yes
      register: apt_updated

    - name: apt safe upgrade
      apt: upgrade=safe
      delay: 1
      ignore_errors: yes
      register: apt_upgraded

    - name: check if reboot is required
      stat: path=/var/run/reboot-required
      register: rb

    - name: Reboot if necessary
      reboot:
        reboot_timeout: 3600
      ignore_errors: true
      when: rb.stat.exists

    - name: Delete reboot-required file 
      file:
        path: /var/run/reboot-required
        state: absent
      ignore_errors: true

- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install requisite 32-bit libraries
      apt:
        name:  "{{ packages }}"
        state: present
        update_cache:  yes
      vars:
        packages:
          - lib32gcc1
          - lib32stdc++6
          - libc6-i386
          - libcurl4-gnutls-dev:i386
          - screen
          - python-pip
          - python-apt
          - libxerces-c-dev:i386 
          - gdb

- hosts: all
  vars:
    port: 27020
  become: yes
  become_method: sudo
  tasks:
    - name: UFW allow SSH
      ufw: rule=allow port=22 proto=any
      ignore_errors: True

    - name: UFW allow SteamCMD
      ufw: rule=allow port=4380 proto=any
      ignore_errors: True

    - name: UFW allow SteamCMD
      ufw: rule=allow port=10999 proto=any
      ignore_errors: True

    - name: UFW allow SteamCMD
      ufw: rule=allow port=7777 proto=any
      ignore_errors: True

    - name: UFW allow SteamCMD
      ufw: rule=allow port=27015 proto=any
      ignore_errors: True

    - name: UFW allow SteamCMD
      ufw: rule=allow port={{port}} proto=any
      ignore_errors: True

    - name: UFW enable
      ufw: state=enabled
      ignore_errors: True

- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: apt update
      apt: update-cache=yes cache_valid_time=3600
      retries: 3
      delay: 1
      ignore_errors: yes
      register: apt_updated

    - name: apt safe upgrade
      apt: upgrade=safe
      delay: 1
      ignore_errors: yes
      register: apt_upgraded

    - name: Reboot for clean start
      reboot:
        reboot_timeout: 3600
      ignore_errors: true

- hosts: all
  become: yes
  become_method: sudo
  vars:
    ssh_user: ubuntu
    url: http://media.steampowered.com/installer/steamcmd_linux.tar.gz
  tasks:
    - name: Sets Steam folder
      file: path=/home/{{ssh_user}}/Steam owner={{ssh_user}} group={{ssh_user}} state=directory mode=0775
      ignore_errors: True

    - name: Download SteamCMD
      get_url:
        url: "{{url}}"
        dest: /home/{{ssh_user}}/Steam/steamcmd_linux.tar.gz
        mode: '0664'

    - name: Unarchive SteamCMD
      unarchive:
        src: /home/{{ssh_user}}/Steam/steamcmd_linux.tar.gz
        dest: /home/{{ssh_user}}/Steam
        remote_src: yes

    - name: Delete file steamcmd_linux.tar.gz
      file:
        path: /home/{{ssh_user}}/Steam/steamcmd_linux.tar.gz
        state: absent

- hosts: all
  vars:
    ssh_user: ubuntu
  become: yes
  become_method: sudo
  become_user: "{{ssh_user}}"
  tasks:
    - name: Create game script for Left 4 Dead 2
      template: src=static_files/l4d2.j2 dest=/home/{{ssh_user}}/Steam/l4d2.txt owner={{ssh_user}} group={{ssh_user}} mode=0644
  
    - name: Run the SteamCMD setup for Left 4 Dead 2
      shell: './steamcmd.sh +runscript /home/{{ssh_user}}/Steam/l4d2.txt'
      args:
        chdir: /home/{{ssh_user}}/Steam/
      ignore_errors: True

- hosts: all
  vars:
    hostname: "Newer Win"
    rcon_password: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters') }}"
    sv_contact: "nw@example.com"
    ssh_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: Upload server.cfg
      template: src=static_files/server.j2 dest=/home/{{ssh_user}}/Steam/L4D2-server/left4dead2/cfg/server.cfg owner={{ssh_user}} group={{ssh_user}} mode=0644
      ignore_errors: True

- hosts: all
  become: yes
  become_method: sudo
  vars:
    ssh_user: ubuntu
  tasks:
    - name: Sets .steam folder
      file: path=/home/{{ssh_user}}/.steam owner={{ssh_user}} group={{ssh_user}} state=directory mode=0775
      ignore_errors: True

    - name: Sets sdk32 folder
      file: path=/home/{{ssh_user}}/.steam/sdk32 owner={{ssh_user}} group={{ssh_user}} state=directory mode=0775
      ignore_errors: True
      
    - name: Copy steamclient.so
      copy: remote_src=True src=/home/{{ssh_user}}/Steam/linux32/steamclient.so dest=/home/{{ssh_user}}/.steam/sdk32/steamclient.so
      ignore_errors: True

- hosts: all
  vars:
    ssh_user: ubuntu
    port: 27020
  become: yes
  become_method: sudo
  tasks:
    - name: Upload l4d2.service
      template: src=static_files/l4d2.service.j2 dest=/etc/systemd/system/l4d2.service owner=root group=root mode=0644
      ignore_errors: True

    - name: force systemd to reread configs
      systemd: daemon_reload=yes

    - name: enable l4d2.service
      systemd:
        name: l4d2
        state: started
        enabled: True
